### ISSUE TITLE
Navbar does not scale to high number of messages

### ISSUE THREAD

**Issue by zetaab** [espoon-voltti/evaka#4207]
<img width="509" alt="Screenshot 2023-10-03 at 15 01 25" src="https://github.com/espoon-voltti/evaka/assets/22482503/a269d9cc-a09e-4687-95ea-187efd4094ef">

When there are more than n messages (where n something like >10 or >100), its quite difficult to see the exact number anymore. The circle does not scale after "Viestit". Perhaps worth of using like badge or tag component instead?

**Comment by Wnt** [comment]
Thanks for reporting this! This has now been fixed and the fix is included in all evaka production versions as of now.
