### ISSUE TITLE
What is the point of number 1 after the children name?

### ISSUE THREAD

**Issue by zetaab** [espoon-voltti/evaka#4208]
<img width="509" alt="Screenshot 2023-10-03 at 15 01 25" src="https://github.com/espoon-voltti/evaka/assets/22482503/46094985-3cb2-4ebf-9fd4-308b24a54d30">

Why there is number 1 after children name? I have tried to think use-case for that. Can single person be more than one children?

**Comment by akheron** [comment]
It's the total number of notifications for the child. You should see the individual notification counts further down the child's page.

![image](https://github.com/espoon-voltti/evaka/assets/70927/24cf5c7d-0609-47af-a5c8-28e62de366f9)

**Comment by zetaab** [comment]
yeah might make sense
