### ISSUE TITLE
Login session does not persist on mobile device

### ISSUE THREAD

**Issue by hamalaiv** [espoon-voltti/evaka#5126]
As a user it is quite annoying to have to login every time I open the site. Would it be possible for the session to persist? And I'm talking about the weak login only here. 

I'm using Chrome on my phone and added the site to my home screen. I have Android version 12 and Chrome version 124.0.6367.113.

**Comment by reynders** [comment]
Thank you for the input. We understand your point about the login session being too short. The current 30min mobile web application session duration is based on general security guidelines. Your feedback has been duly noted.

**Comment by LimmaPaulus** [comment]
Moi,

Sallinette vielä kommentoida tähän. Pahoittelut, että en jaksa alkaa tähän englantia vääntämään.
 
eVaka on käytettävyydeltään ylivoimaisesti paras julkisen puolen ohjelmisto, mihin olen törmännyt. Se on yksinkertaisesti erittäin toimiva ja selkeä kaikin puolin. Valitettavasti se on vain todella työläs avata. Ensinnäkin pitää aina avata selain ja näppäillä osoite. Sitten pitää vielä kirjautua.

Itse salasanamanageria käyttävänä pääsen kirjautumaan kohtuullisen nopeasti. Vaimoltani jää kuitenkin iso osa viesteistä lukematta sen vuoksi, että kirjautuminen on liian työlästä (sietää toki hänen hävetä itsensäkin).

Kaikkien kavereideni palaute on samaa. Hyvä ohjelma, mutta päällimmäiseksi nousee aina kirjautumisen työläys. Päiväkodista tulee viestejä lähes päivittäin. Tällä tavalla niiden lukeminen on oikeasti rasittavan työlästä.

Miettisin tätä ihan tosissaan käytettävyys-tietoturva-akselilla. Kysessä on tosiaan vain rajattu kirjautuminen, jolla ei näe mitään lasten henkilötietoja. Joillakin huoltajilla voi ehkä olla jotain sensitiivisiä viestejä lähetettynä. Viesteistäkin suurin osa on kuitenkin päiväkodilta tulevia.

Verratkaa tätä nyt siihen, että WhatsAppissa tai Instagramissa on ikuiset laitekohtaiset sessiot ainakin mobiililaitteilla. Parin päivän sessio on tietoturvariskinä mielestäni hyvin maltillinen, ja tuollaiset puolen tunnin sessiot kuuluvat nähdäkseni lähinnä pankkisovelluksiin.

Lyhyiden sessioiden lisäksi mobiilisovelluksen puute on mielestäni myös merkittävä ongelma, vaikka webbisovellus kännykällä toimiikin hyvin.

Ehdotukseni:

- Muuttakaa sessiot esimerkiksi kolmen päivän pituisiksi.
- Tehkää PWA. Se tulee varmasti mitättömällä työllä
- Tehkää wrapperisovellukset sovelluskauppoihin, koska PWA on monille liian epämääräinen
- Lähettäkää push-ilmoitukset uusista eVakaan tulleista viesteistä
- Jos ette tee push-viestejä, laittakaa mobiilisovellus avaamaan uudesta viestistä ilmoittavan sähköpostiviestin linkki suoraan viestiin
