### ISSUE TITLE
Should input type email or phone be used instead of text?

### ISSUE THREAD

**Issue by hamalaiv** [espoon-voltti/evaka#5128]
I noticed that many of the inputs are type text. Should you use type email or phone when appropriate? For example the personal details page has both email and phone input.

The correct type helps on mobile devices because you get faster autocomplete for email and correct keyboard layout.

I could make this change if you are ok with it.

ps. login page email input is also "text" but I don't know if it can be changed?

**Comment by reynders** [comment]
Thank you for the input. This suggestion has been added to the product backlog.
